// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgseyxlqqgujwgqbjkdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnc2V5eGxxcWd1andncWJqa2RpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjgyMjUsImV4cCI6MjA2NTE0NDIyNX0.njR3JZbYVww4bWVyE4yCRu8kJ9066XRY05zWRzqclw0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);